#!/bin/bash

args="-Wall -Wextra -Wno-unused-parameter"

echo "Cleaning..."
rm -f *.o toast
echo "Compiling..."
gcc -g $args -c sha1.c
gcc -g $args -c luaobj.c
gcc -g $args -c toast.c
echo "Linking..."
gcc -g $args -o toast toast.o sha1.o luaobj.o -levent -llua
