#!/bin/bash

rm -f toast toast.o sha1.o
gcc -g -Wall -Wextra -Wno-unused-parameter -c sha1.c
gcc -g -Wall -Wextra -Wno-unused-parameter -c toast.c
gcc -g -Wall -Wextra -Wno-unused-parameter -o toast toast.o sha1.o -levent -llua
